### ISSUE TITLE
Game Link IDEA

### ISSUE THREAD

**Issue by MrMdemiC** [lorddusk/DuskBotIssues#12]
If you are playing a game that a use will type !game and than the bot shows the game name and optional if its in the steam store, the steam link:

So example 1 (Non Steam Store Game):
Lorddusk is playing Minecraft.
In chat MrMdemiC Types !Game
durskbot Response: MrMdemiC, Lorddusk is currently playing Minecraft!

So example 2 (Steam Store Game):
Lorddusk is playing AdVenture Capitalist.
In chat MrMdemiC Types !Game
durskbot Response: MrMdemiC, Lorddusk is currently playing AdVenture Capitalist! http://store.steampowered.com/app/346900.

Thats my idea!!

**Comment by lorddusk** [comment]
Will be in 1.0.3
