### ISSUE TITLE
Togglestream option

### ISSUE THREAD

**Issue by ArashiDragon** [lorddusk/DuskBotIssues#15]
When !togglestream is used and the bot is ending the stream (giving of points), have it display the uptime between stream start and end.

**Comment by lorddusk** [comment]
No, this is something I specifically don't want to add. Not everyone that uses my bot wants to know this. I've asked before to a few of my users, and they all didn't want it. And I'm not going to create another toggle for just this small addition.

**Comment by ArashiDragon** [comment]
Could you pissibly make this info show in the bot window? Doesn't have to ne in chat...
