### ISSUE TITLE
!songrequest Has the ability to request the same song multiple times from the same person

### ISSUE THREAD

**Issue by ghost** [lorddusk/DuskBotIssues#16]
While I think multiple people requesting the same song is a good thing the same person requesting the same song multiple times might be spammy and rather bad. Here's a screenshot of what I mean. 
EDIT: And it didn't attach the screenshot :/ Should be fixed now hopefully
![botissue](https://cloud.githubusercontent.com/assets/7614378/8161356/bb19b206-13b9-11e5-8963-f8d063654bec.png)

**Comment by lorddusk** [comment]
Non-Issue
