### ISSUE TITLE
!<points> clear [username|all]

### ISSUE THREAD

**Issue by ArashiDragon** [lorddusk/DuskBotIssues#3]
to clear the points of a user, OR clear all points for those that may want to reset points monthly or for similar reasons.

clear all (for safety) may want to require a confirmation response, like
!points clear all
bot responds "Confirm Clearing all Points by typing '!clear points now' "
!clear points now
bot responds "All points cleared".

Or something similar.

**Comment by lorddusk** [comment]
Added in 1.0.2
