### ISSUE TITLE
!timer (alternate replacement)

### ISSUE THREAD

**Issue by ArashiDragon** [lorddusk/DuskBotIssues#4]
!timer <name> [command/text] <time in minutes> [count] <command/text> "create a new timer"
<name> "Timer name"
[command/text] "Optional command or text to output"
<time in minutes> "How often to trigger timer"
[count] "How many times to repeat timer" leave blank for single use, use -1 for infinite.
<command/text> "command or text to repeat Y times ever X minutes"

!timerlist "lists active timers"
!timerstop <name> "stops the named timer"

**Comment by lorddusk** [comment]
I made something like this. It's a schedule command. It will loop through messages each x minutes. And goes through them all, then resets to the first.

V1.0.3
