### ISSUE TITLE
Possibility of making sure the bot is only running once in processes

### ISSUE THREAD

**Issue by ArashiDragon** [lorddusk/DuskBotIssues#5]
Not a coder so not sure how difficult this would be, but in windows, a PID is created for the bot. I noticed another issue where you told the person to stop one copy of the bot. Maybe you could have a way for the bot to check if it's already running. (at least if started from the same start script)

**Comment by lorddusk** [comment]
Tried, It can't fix this for Windows. because the PID is fluctuent. Linux/Mac have something for this already.

**Comment by ArashiDragon** [comment]
Not a programer so not sure how it's done, but I know of two ways I've seen this handled before.

1) Capture the PID assigned to the process when it's started.
2) (suggested by a friend) Should be a way to find the .exe in the running processes. This would only prevent the same "name.exe" from running, but if a copy were made "name2.exe" it wouldn't match so would run.

**Comment by lorddusk** [comment]
Open 2 wouldnt be possible. since it's running as javaw.exe. Open 1 might be viable. But when you open it twice. It will just create a second PID. so might be viable after all.
