### ISSUE TITLE
Kill / Shutdown command

### ISSUE THREAD

**Issue by ArashiDragon** [lorddusk/DuskBotIssues#8]
Instead of just force closing the cmd/bat file that runs the bot, maybe a better way would be a kil/shutdown command that can be run to terminate the bot. It would save all files immediately and go through a controlled shutdown.

!shutdown (smod or higher only command)

For safety, maybe require the command run twice, consecutively in short time frame. First time prepares the command, 2nd time confirms you meant to do it.

**Comment by lorddusk** [comment]
Will be in the next release (1.0.4)
